name: Tests for ref implementation

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hash:
          - sha256
          - shake256
          - haraka
        size:
          - 128
          - 192
          - 256
        option:
          - s
          - f
        thash:
          - simple
          - robust
    steps:
      - uses: actions/checkout@v1
      - name: Put params file in place
        run: |
          rm ref/params.h
          cp ref/params/params-sphincs-${{ matrix.hash }}-${{ matrix.size }}${{ matrix.option }}.h ref/params.h
      - name: Setup hash_state.h
        run: |
          rm ref/hash_state.h
          cp ref/hash_states/${{ matrix.hash }}.h ref/hash_state.h
      - name: Run make
        run: |
          make -C ref HASH=${{ matrix.hash }} THASH=${{ matrix.thash }} clean
          make -C ref HASH=${{ matrix.hash }} THASH=${{ matrix.thash }} tests
          make -C ref HASH=${{ matrix.hash }} THASH=${{ matrix.thash }} test
          make -C ref THASH=${{ matrix.thash }} PQCgenKAT_sign
      - name: Run PQCgenKAT_sign
        run: ./ref/PQCgenKAT_sign

#  vim: set ft=yaml ts=2 sw=2 et :
